# Generate demo.gif using https://github.com/charmbracelet/vhs
Output demo.gif

Set Shell "bash"
Set FontSize 32
Set Width 1200
Set Height 600
Set Theme "Catppuccin Macchiato"

Type "echo 'Welcome to kgen!'" Sleep 1s Enter

Sleep 2s

Type "kgen" Sleep 1s Enter

Sleep 2s

Type "com.github.mestru17" Sleep 1s Enter

Sleep 2s

Type "kgen-kotlin" Sleep 1s Enter

Sleep 2s

Type ".kgen" Sleep 1s Enter

Sleep 3s

Type "cd kgen-kotlin" Sleep 1s Enter

Sleep 2s

Type "ls" Sleep 1s Enter

Sleep 5s
