services:
  web:
    build:
      context: .
      args:
        - MAVEN_REPO_URL=${MAVEN_REPO_URL}
        - MAVEN_REPO_USERNAME=${MAVEN_REPO_USERNAME}
        - MAVEN_REPO_PASSWORD=${MAVEN_REPO_PASSWORD}
    volumes:
      ./application.yml:/app/application.yml
